### ISSUE TITLE
Don't export `HashMap`

### ISSUE THREAD

**Issue by aborgna-q** [lmondada/portmatching#49]
Having the crate as a dependency causes `portmatching::HashMap` to be the suggested as a (frequently first) option for importing `HashMap` by rust-analyzer. What's even worse is that this is not the same hashmap in `std::collections`.
![image](https://github.com/lmondada/portmatching/assets/121866228/0c6d980e-82f4-48bf-8f20-d74c466ebc98)

https://github.com/lmondada/portmatching/blob/cddf72c80a492c196a13042610b1966705bc4be5/src/lib.rs#L63

I'd suggest removing the public export, or renaming it so users don't mix it up with the `std` one.

**Comment by lmondada** [comment]
Yes absolutely agree!! Will do that in the refactor if you don't mind.
